name: Update README with Changelog

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Explicitly set permissions for the GitHub token

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          set -x
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog from Commit Messages
        run: |
          set -x

          # Get the latest change and save it to a temp file
          git log -n 1 --pretty=format:"- %s (%ci)" --abbrev-commit > latest_changes.txt

          # Create a new README with the desired order
          {
            echo "# Resume Project"
            echo ""
            echo "A Spring Boot application to manage resume data, including work experience, education, and contact information."
            echo ""
            echo "## Technologies Used"
            echo "- Java (version 23)"
            echo "- Spring Boot"
            echo "- Lombok"
            echo "- Maven"
            echo "- JPA (Java Persistence API)"
            echo ""
            echo "## How to Run"
            echo "1. Clone the repository."
            echo "2. Navigate to the project directory."
            echo "3. Run the following command to start the application:"
            echo "\`\`\`"
            echo "mvn spring-boot:run"
            echo "\`\`\`"
            echo ""
            echo "## Changelog"
            echo "### Latest Changes"
            cat latest_changes.txt
            echo ""
            echo "### Past Commits"
            git log --skip=1 -n 10 --pretty=format:"- %s (%ci)" --abbrev-commit
            echo ""
          } > README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          git checkout -b update-readme-changelog
          git add README.md
          git commit -m "chore: Update README with latest changelog" || echo "Nothing to commit"
          git pull origin main --rebase  # Pull latest changes from the main branch with rebase
          git push origin update-readme-changelog --force  # Force push changes
