name: Update README with Changelog

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Explicitly set permissions for the GitHub token

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          set -x
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog from Commit Messages
        run: |
          set -x
          # Generate latest commit messages for the new Latest Changes
          git log -n 1 --pretty=format:"- %s (%ci)" --abbrev-commit > recent_changelog.txt

          # Append current Latest Changes to Past Commits
          echo "\n### Past Commits" > past_commits.txt
          grep -A1000 "### Latest Changes" README.md | grep -v "### Latest Changes" >> past_commits.txt

          # Update the README with the new structure
          echo "### Latest Changes" > temp_readme.txt
          cat recent_changelog.txt >> temp_readme.txt
          echo "\n" >> temp_readme.txt
          cat past_commits.txt >> temp_readme.txt
          cat README.md >> temp_readme.txt
          mv temp_readme.txt README.md

      - name: Create a new branch, pull, and force push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          git checkout main
          git add README.md
          git commit -m "chore: Update README with latest changelog" || echo "Nothing to commit"
          git pull origin main --rebase || git rebase --abort # Pull latest changes from the main branch with rebase
          git push origin main # Push changes to main 
