name: Update README with Changelog

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Generate Changelog from Commit Messages
        run: |
          git log -n 5 --pretty=format:"- %s (%ci)" --abbrev-commit > recent_changelog.txt
          echo "### Latest Changes" > temp_readme.txt
          cat recent_changelog.txt >> temp_readme.txt
          echo "\n" >> temp_readme.txt
          cat README.md >> temp_readme.txt
          mv temp_readme.txt README.md

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: Update README with latest changelog"
          git push
