name: Update README with Changelog

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          set -x
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog from Commit Messages
        run: |
          set -x
          # Get the latest commit and update "Latest Changes"
          git log -1 --pretty=format:"- %s (%ci)" --abbrev-commit > latest_changes.txt

          # Prepare the updated README content
          echo "## Latest Changes" > temp_readme.txt
          cat latest_changes.txt >> temp_readme.txt
          echo "" >> temp_readme.txt

          echo "## Past Commits" >> temp_readme.txt
          if [ -f past_commits.txt ]; then
            # Append new past commits while retaining the previous history
            cat past_commits.txt >> temp_readme.txt
          fi

          # Update the README
          cat README.md >> temp_readme.txt
          mv temp_readme.txt README.md

          # Update past commits log for the next run
          echo "## Past Commits" > past_commits.txt
          git log --skip=1 --pretty=format:"- %s (%ci)" --abbrev-commit >> past_commits.txt

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          git add README.md past_commits.txt
          git commit -m "chore: Update README with latest changelog"
          git push origin main
